#!/bin/sh
san_iface_mac_address=$(cat /sys/firmware/ibft/ethernet0/mac)

for iface in $(ls -1 /sys/class/net/); do
    iface_addr=$(cat /sys/class/net/"$iface"/address)
    if [ "$iface_addr" = "$san_iface_mac_address" ]; then
        /sbin/ip route delete default dev "$iface"
        break;
    fi
done

exit 0